python3 train.py  --experiment wuzhou_CAM_focal_m0.0_weight_global --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss MultiFocalLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.0 --save_check_point false  --force_save_last true  --weight_loss true --weight_type pixel --device_id 4
python3 train.py  --experiment wuzhou_CAM_focal_m0.1_weight_global --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss MultiFocalLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.1 --save_check_point false  --force_save_last true  --weight_loss true --weight_type pixel --device_id 4
python3 train.py  --experiment wuzhou_CAM_focal_m0.2_weight_global --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss MultiFocalLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.2 --save_check_point false  --force_save_last true  --weight_loss true --weight_type pixel --device_id 4
python3 train.py  --experiment wuzhou_CAM_focal_m0.3_weight_global --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss MultiFocalLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.3 --save_check_point false  --force_save_last true  --weight_loss true --weight_type pixel --device_id 4
python3 train.py  --experiment wuzhou_CAM_focal_m0.4_weight_global --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss MultiFocalLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.4 --save_check_point false  --force_save_last true  --weight_loss true --weight_type pixel --device_id 4
python3 train.py  --experiment wuzhou_CAM_focal_m0.5_weight_global --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss MultiFocalLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.5 --save_check_point false  --force_save_last true  --weight_loss true --weight_type pixel --device_id 4
python3 train.py  --experiment wuzhou_CAM_focal_m0.6_weight_global --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss MultiFocalLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.6 --save_check_point false  --force_save_last true  --weight_loss true --weight_type pixel --device_id 4
python3 train.py  --experiment wuzhou_CAM_focal_m0.7_weight_global --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss MultiFocalLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.7 --save_check_point false  --force_save_last true  --weight_loss true --weight_type pixel --device_id 4
python3 train.py  --experiment wuzhou_CAM_focal_m0.8_weight_global --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss MultiFocalLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.8 --save_check_point false  --force_save_last true  --weight_loss true --weight_type pixel --device_id 4
python3 train.py  --experiment wuzhou_CAM_focal_m0.9_weight_global --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss MultiFocalLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.9 --save_check_point false  --force_save_last true  --weight_loss true --weight_type pixel --device_id 4

python3 train.py  --experiment wuzhou_CAM_focal_m91_weight_global --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss MultiFocalLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.91 --save_check_point false  --force_save_last true  --weight_loss true --weight_type pixel --device_id 4
python3 train.py  --experiment wuzhou_CAM_focal_m92_weight_global --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss MultiFocalLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.92 --save_check_point false  --force_save_last true  --weight_loss true --weight_type pixel --device_id 4
python3 train.py  --experiment wuzhou_CAM_focal_m93_weight_global --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss MultiFocalLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.93 --save_check_point false  --force_save_last true  --weight_loss true --weight_type pixel --device_id 4
python3 train.py  --experiment wuzhou_CAM_focal_m94_weight_global --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss MultiFocalLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.94 --save_check_point false  --force_save_last true  --weight_loss true --weight_type pixel --device_id 4
python3 train.py  --experiment wuzhou_CAM_focal_m95_weight_global --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss MultiFocalLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.95 --save_check_point false  --force_save_last true  --weight_loss true --weight_type pixel --device_id 4
python3 train.py  --experiment wuzhou_CAM_focal_m96_weight_global --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss MultiFocalLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.96 --save_check_point false  --force_save_last true  --weight_loss true --weight_type pixel --device_id 4
python3 train.py  --experiment wuzhou_CAM_focal_m97_weight_global --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss MultiFocalLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.97 --save_check_point false  --force_save_last true  --weight_loss true --weight_type pixel --device_id 4
python3 train.py  --experiment wuzhou_CAM_focal_m98_weight_global --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss MultiFocalLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.98 --save_check_point false  --force_save_last true  --weight_loss true --weight_type pixel --device_id 4
python3 train.py  --experiment wuzhou_CAM_focal_m99_weight_global --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss MultiFocalLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.99 --save_check_point false  --force_save_last true  --weight_loss true --weight_type pixel --device_id 4

