python3 train.py  --experiment CAM_ce_m0.0_weight_baseline_global_prior --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss WeightCrossEntropyLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.0 --save_check_point false  --force_save_last true  --weight_loss true --weight_type baseline_global_prior --device_id 6
python3 train.py  --experiment CAM_ce_m0.1_weight_baseline_global_prior --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss WeightCrossEntropyLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.1 --save_check_point false  --force_save_last true  --weight_loss true --weight_type baseline_global_prior --device_id 6
python3 train.py  --experiment CAM_ce_m0.2_weight_baseline_global_prior --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss WeightCrossEntropyLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.2 --save_check_point false  --force_save_last true  --weight_loss true --weight_type baseline_global_prior --device_id 6
python3 train.py  --experiment CAM_ce_m0.3_weight_baseline_global_prior --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss WeightCrossEntropyLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.3 --save_check_point false  --force_save_last true  --weight_loss true --weight_type baseline_global_prior --device_id 6
python3 train.py  --experiment CAM_ce_m0.4_weight_baseline_global_prior --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss WeightCrossEntropyLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.4 --save_check_point false  --force_save_last true  --weight_loss true --weight_type baseline_global_prior --device_id 6
python3 train.py  --experiment CAM_ce_m0.5_weight_baseline_global_prior --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss WeightCrossEntropyLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.5 --save_check_point false  --force_save_last true  --weight_loss true --weight_type baseline_global_prior --device_id 6
python3 train.py  --experiment CAM_ce_m0.6_weight_baseline_global_prior --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss WeightCrossEntropyLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.6 --save_check_point false  --force_save_last true  --weight_loss true --weight_type baseline_global_prior --device_id 6
python3 train.py  --experiment CAM_ce_m0.7_weight_baseline_global_prior --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss WeightCrossEntropyLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.7 --save_check_point false  --force_save_last true  --weight_loss true --weight_type baseline_global_prior --device_id 6
python3 train.py  --experiment CAM_ce_m0.8_weight_baseline_global_prior --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss WeightCrossEntropyLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.8 --save_check_point false  --force_save_last true  --weight_loss true --weight_type baseline_global_prior --device_id 6
python3 train.py  --experiment CAM_ce_m0.9_weight_baseline_global_prior --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss WeightCrossEntropyLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.9 --save_check_point false  --force_save_last true  --weight_loss true --weight_type baseline_global_prior --device_id 6

python3 train.py  --experiment CAM_ce_m91_weight_baseline_global_prior --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss WeightCrossEntropyLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.91 --save_check_point false  --force_save_last true  --weight_loss true --weight_type baseline_global_prior --device_id 6
python3 train.py  --experiment CAM_ce_m92_weight_baseline_global_prior --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss WeightCrossEntropyLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.92 --save_check_point false  --force_save_last true  --weight_loss true --weight_type baseline_global_prior --device_id 6
python3 train.py  --experiment CAM_ce_m93_weight_baseline_global_prior --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss WeightCrossEntropyLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.93 --save_check_point false  --force_save_last true  --weight_loss true --weight_type baseline_global_prior --device_id 6
python3 train.py  --experiment CAM_ce_m94_weight_baseline_global_prior --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss WeightCrossEntropyLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.94 --save_check_point false  --force_save_last true  --weight_loss true --weight_type baseline_global_prior --device_id 6
python3 train.py  --experiment CAM_ce_m95_weight_baseline_global_prior --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss WeightCrossEntropyLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.95 --save_check_point false  --force_save_last true  --weight_loss true --weight_type baseline_global_prior --device_id 6
python3 train.py  --experiment CAM_ce_m96_weight_baseline_global_prior --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss WeightCrossEntropyLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.96 --save_check_point false  --force_save_last true  --weight_loss true --weight_type baseline_global_prior --device_id 6
python3 train.py  --experiment CAM_ce_m97_weight_baseline_global_prior --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss WeightCrossEntropyLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.97 --save_check_point false  --force_save_last true  --weight_loss true --weight_type baseline_global_prior --device_id 6
python3 train.py  --experiment CAM_ce_m98_weight_baseline_global_prior --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss WeightCrossEntropyLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.98 --save_check_point false  --force_save_last true  --weight_loss true --weight_type baseline_global_prior --device_id 6
python3 train.py  --experiment wuzhou_CAM_ce_m99_weight_baseline_global_prior --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss WeightCrossEntropyLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.99 --save_check_point false  --force_save_last true  --weight_loss true --weight_type baseline_global_prior --device_id 6

