python3 modelchekcer_apd.py --load ./checkpoint/CP_ex.asl_baseline_epoch30_UNet_Cam2007DatasetV2.pth
python3 modelchekcer_apd.py --load ./checkpoint/CP_ex.asl_bnout_epoch30_UNetBnout_Cam2007DatasetV2.pth
python3 modelchekcer_apd.py --load ./checkpoint/CP_ex.asl_epoch30_UNet_Cam2007DatasetV2.pth
python3 modelchekcer_apd.py --load ./checkpoint/CP_ex.ce_baseline_epoch30_UNet_Cam2007DatasetV2.pth
python3 modelchekcer_apd.py --load ./checkpoint/CP_ex.ce_bnout_df_epoch30_UNetBnout_Cam2007DatasetV2.pth
python3 modelchekcer_apd.py --load ./checkpoint/CP_ex.ce_epoch30_UNet_Cam2007DatasetV2.pth
python3 modelchekcer_apd.py --load ./checkpoint/CP_ex.ce_floatfilter_epoch30_UNet_Cam2007DatasetV2.pth
python3 modelchekcer_apd.py --load ./checkpoint/CP_ex.ce_tde_epoch30_UNetTDE_Cam2007DatasetV2.pth
python3 modelchekcer_apd.py --load ./checkpoint/CP_ex.ce_wrecall_epoch30_UNet_Cam2007DatasetV2.pth
python3 modelchekcer_apd.py --load ./checkpoint/CP_ex.ce_wrecall_gn_epoch30_UNet_Cam2007DatasetV2.pth
python3 modelchekcer_apd.py --load ./checkpoint/CP_ex.focal_baseline_epoch30_UNet_Cam2007DatasetV2.pth
python3 modelchekcer_apd.py --load ./checkpoint/CP_ex.focal_bnout_epoch30_UNetBnout_Cam2007DatasetV2.pth
python3 modelchekcer_apd.py --load ./checkpoint/CP_ex.focal_epoch30_UNet_Cam2007DatasetV2.pth
python3 modelchekcer_apd.py --load ./checkpoint/CP_ex.focal_floatfilter_epoch30_UNet_Cam2007DatasetV2.pth
python3 modelchekcer_apd.py --load ./checkpoint/CP_ex.focal_wrecall_epoch30_UNet_Cam2007DatasetV2.pth
python3 modelchekcer_apd.py --load ./checkpoint/CP_ex.focal_wrecall_gn_epoch30_UNet_Cam2007DatasetV2.pth
python3 modelchekcer_apd.py --load ./checkpoint/CP_ex.norm_ce_bnout_epoch30_UNetBnout_Cam2007DatasetV2.pth
python3 modelchekcer_apd.py --load ./checkpoint/CP_ex.norm_ce_epoch30_UNet_Cam2007DatasetV2.pth
python3 modelchekcer_apd.py --load ./checkpoint/CP_ex.wce_bnout_epoch30_UNetBnout_Cam2007DatasetV2.pth
python3 modelchekcer_apd.py --load ./checkpoint/CP_ex.focal_tde_epoch30_UNetTDE_Cam2007DatasetV2.pth
