# python3 train.py --experiment batch  --dataset CityScapesDataset --data_dir  ./data/city_scapes  --input_channels 3  --num_classes 19 --batch-size 1 --arch FCNN2 --deep_supervision false --optimizer SGD  --weight_loss true  --loss CrossEntropyLoss  --epochs 10 --learning-rate 1e-2  --momentum 0.99 --save_check_point false  --force_save_last true --batch-size 8
#python3 train.py  --experiment accumulation_step --dataset CityScapesDataset --data_dir  ./data/city_scapes  --input_channels 3  --num_classes 19 --batch-size 1 --arch FCNN2 --deep_supervision false --optimizer SGD  --weight_loss true  --loss CrossEntropyLoss  --epochs 10 --learning-rate 1e-2  --momentum 0.99 --save_check_point false  --force_save_last true --accumulation-step 8

#python3 train.py  --experiment std --dataset CityScapesDataset --data_dir  ./data/city_scapes  --input_channels 3  --num_classes 19 --batch-size 1 --arch FCNN2 --deep_supervision false --optimizer SGD  --weight_loss true  --loss CrossEntropyLoss  --epochs 10 --learning-rate 1e-2  --momentum 0.99 --save_check_point false  --force_save_last true
#python3 train.py  --experiment accumulation_step001 --dataset CityScapesDataset --data_dir  ./data/city_scapes  --input_channels 3  --num_classes 19  --arch FCNN2 --deep_supervision false --optimizer SGD  --weight_loss true  --loss CrossEntropyLoss  --epochs 20 --learning-rate 1e-2  --momentum 0.99 --save_check_point false  --force_save_last true --accumulation-step 8
#python3 train.py  --experiment accumulation_step002 --dataset CityScapesDataset --data_dir  ./data/city_scapes  --input_channels 3  --num_classes 19  --arch FCNN2 --deep_supervision false --optimizer SGD  --weight_loss true  --loss CrossEntropyLoss  --epochs 20 --learning-rate 1e-2  --momentum 0.99 --save_check_point false  --force_save_last true --accumulation-step 16
#python3 train.py  --experiment accumulation_step003 --dataset CityScapesDataset --data_dir  ./data/city_scapes  --input_channels 3  --num_classes 19  --arch FCNN2 --deep_supervision false --optimizer SGD  --weight_loss true  --loss CrossEntropyLoss  --epochs 20 --learning-rate 1e-2  --momentum 0.99 --save_check_point false  --force_save_last true --accumulation-step 32
#python3 train.py  --experiment accumulation_step004 --dataset CityScapesDataset --data_dir  ./data/city_scapes  --input_channels 3  --num_classes 19  --arch FCNN2 --deep_supervision false --optimizer SGD  --weight_loss true  --loss CrossEntropyLoss  --epochs 20 --learning-rate 1e-2  --momentum 0.99 --save_check_point false  --force_save_last true --accumulation-step 64

# python3 train.py  --experiment accumulation_step001 --dataset CityScapesDataset --data_dir  ./data/city_scapes  --input_channels 3  --num_classes 19  --arch FCNN2 --deep_supervision false --optimizer SGD  --weight_loss true  --loss CrossEntropyLoss  --epochs 20 --learning-rate 1e-2  --momentum 0 --save_check_point false  --force_save_last true --accumulation-step 8
# python3 train.py  --experiment accumulation_step002 --dataset CityScapesDataset --data_dir  ./data/city_scapes  --input_channels 3  --num_classes 19  --arch FCNN2 --deep_supervision false --optimizer SGD  --weight_loss true  --loss CrossEntropyLoss  --epochs 20 --learning-rate 1e-2  --momentum 0 --save_check_point false  --force_save_last true --accumulation-step 16
# python3 train.py  --experiment accumulation_step003 --dataset CityScapesDataset --data_dir  ./data/city_scapes  --input_channels 3  --num_classes 19  --arch FCNN2 --deep_supervision false --optimizer SGD  --weight_loss true  --loss CrossEntropyLoss  --epochs 20 --learning-rate 1e-2  --momentum 0 --save_check_point false  --force_save_last true --accumulation-step 32
python3 train.py  --experiment accumulation_step004A --dataset CityScapesDataset --data_dir  ./data/city_scapes  --input_channels 3  --num_classes 19  --arch FCNN2 --deep_supervision false --optimizer SGD  --weight_loss true  --loss CrossEntropyLoss  --epochs 20 --learning-rate 1e-2  --momentum 0.1 --save_check_point false  --force_save_last true --accumulation-step 64
python3 train.py  --experiment accumulation_step004B --dataset CityScapesDataset --data_dir  ./data/city_scapes  --input_channels 3  --num_classes 19  --arch FCNN2 --deep_supervision false --optimizer SGD  --weight_loss true  --loss CrossEntropyLoss  --epochs 20 --learning-rate 1e-2  --momentum 0.3 --save_check_point false  --force_save_last true --accumulation-step 64
python3 train.py  --experiment accumulation_step004C --dataset CityScapesDataset --data_dir  ./data/city_scapes  --input_channels 3  --num_classes 19  --arch FCNN2 --deep_supervision false --optimizer SGD  --weight_loss true  --loss CrossEntropyLoss  --epochs 20 --learning-rate 1e-2  --momentum 0.5 --save_check_point false  --force_save_last true --accumulation-step 64
python3 train.py  --experiment accumulation_step004D --dataset CityScapesDataset --data_dir  ./data/city_scapes  --input_channels 3  --num_classes 19  --arch FCNN2 --deep_supervision false --optimizer SGD  --weight_loss true  --loss CrossEntropyLoss  --epochs 20 --learning-rate 1e-2  --momentum 0.7 --save_check_point false  --force_save_last true --accumulation-step 64
python3 train.py  --experiment accumulation_step004E --dataset CityScapesDataset --data_dir  ./data/city_scapes  --input_channels 3  --num_classes 19  --arch FCNN2 --deep_supervision false --optimizer SGD  --weight_loss true  --loss CrossEntropyLoss  --epochs 20 --learning-rate 1e-2  --momentum 0.9 --save_check_point false  --force_save_last true --accumulation-step 64

python3 train.py  --experiment accumulation_step004F --dataset CityScapesDataset --data_dir  ./data/city_scapes  --input_channels 3  --num_classes 19  --arch FCNN2 --deep_supervision false --optimizer SGD  --weight_loss true  --loss CrossEntropyLoss  --epochs 60 --learning-rate 1e-2  --momentum 0.9 --save_check_point false  --force_save_last true --accumulation-step 64
