python3 ./results_summary/zhe_modelchecker_apd.py --experiment focal_bnout_apd --experiment_name "FOCAL BNout"
python3 ./results_summary/zhe_modelchecker_apd.py --experiment asl_bnout_apd --experiment_name "ASL BNout"
python3 ./results_summary/zhe_modelchecker_apd.py --experiment ce_tde_apd --experiment_name "CE TDE"
python3 ./results_summary/zhe_modelchecker_apd.py --experiment focal_tde_apd --experiment_name "FOCAL TDE"
python3 ./results_summary/zhe_modelchecker_apd.py --experiment wce_bnout_apd --experiment_name "WCE BNout"
python3 ./results_summary/zhe_modelchecker_apd.py --experiment norm_ce_apd --experiment_name "NORM CE"
python3 ./results_summary/zhe_modelchecker_apd.py --experiment norm_ce_bnout_apd --experiment_name "NORM CE BNout"
python3 ./results_summary/zhe_modelchecker_apd.py --experiment focal_wrecall_gn_apd --experiment_name "FOCAL WRECALL GN"
python3 ./results_summary/zhe_modelchecker_apd.py --experiment focal_wrecall_apd --experiment_name "FOCAL WRECALL"
python3 ./results_summary/zhe_modelchecker_apd.py --experiment focal_floatfilter_apd --experiment_name "FOCAL DF"
python3 ./results_summary/zhe_modelchecker_apd.py --experiment focal_apd --experiment_name "FOCAL"
python3 ./results_summary/zhe_modelchecker_apd.py --experiment focal_baseline_apd --experiment_name "FOCAL IW"
python3 ./results_summary/zhe_modelchecker_apd.py --experiment ce_wrecall_gn_apd --experiment_name "CE WRECALL GN"
python3 ./results_summary/zhe_modelchecker_apd.py --experiment ce_wrecall_apd --experiment_name "CE WRECALL"
python3 ./results_summary/zhe_modelchecker_apd.py --experiment ce_floatfilter_apd --experiment_name "CE DF"
python3 ./results_summary/zhe_modelchecker_apd.py --experiment ce_apd --experiment_name "CE"
python3 ./results_summary/zhe_modelchecker_apd.py --experiment ce_bnout_df_apd --experiment_name "CE BNout DF"
python3 ./results_summary/zhe_modelchecker_apd.py --experiment ce_baseline_apd --experiment_name "CE IW"
python3 ./results_summary/zhe_modelchecker_apd.py --experiment asl_apd --experiment_name "ASL"
python3 ./results_summary/zhe_modelchecker_apd.py --experiment asl_baseline_apd --experiment_name "ASL IW"
