
python3 train.py  --experiment wuzhou_CAM_focal_m91 --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss MultiFocalLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.91 --save_check_point false  --force_save_last true  --weight_loss false --weight_type pixel --device_id 6
python3 train.py  --experiment wuzhou_CAM_focal_m92 --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss MultiFocalLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.92 --save_check_point false  --force_save_last true  --weight_loss false --weight_type pixel --device_id 6
python3 train.py  --experiment wuzhou_CAM_focal_m93 --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss MultiFocalLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.93 --save_check_point false  --force_save_last true  --weight_loss false --weight_type pixel --device_id 6
python3 train.py  --experiment wuzhou_CAM_focal_m94 --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss MultiFocalLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.94 --save_check_point false  --force_save_last true  --weight_loss false --weight_type pixel --device_id 6
python3 train.py  --experiment wuzhou_CAM_focal_m95 --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss MultiFocalLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.95 --save_check_point false  --force_save_last true  --weight_loss false --weight_type pixel --device_id 6
python3 train.py  --experiment wuzhou_CAM_focal_m96 --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss MultiFocalLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.96 --save_check_point false  --force_save_last true  --weight_loss false --weight_type pixel --device_id 6
python3 train.py  --experiment wuzhou_CAM_focal_m97 --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss MultiFocalLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.97 --save_check_point false  --force_save_last true  --weight_loss false --weight_type pixel --device_id 6
python3 train.py  --experiment wuzhou_CAM_focal_m98 --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss MultiFocalLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.98 --save_check_point false  --force_save_last true  --weight_loss false --weight_type pixel --device_id 6
python3 train.py  --experiment wuzhou_CAM_focal_m99 --dataset Cam2007Dataset --data_dir  ./data/Cam2007_n  --input_channels 3  --num_classes 32 --batch-size 1 --arch UNet --deep_supervision false --optimizer SGD   --loss MultiFocalLoss  --epochs 30 --learning-rate 1e-2  --momentum 0.99 --save_check_point false  --force_save_last true  --weight_loss false --weight_type pixel --device_id 6

